vars:
  project: ???
  data: <PATH>/data

# the account name is only used to describe from which account the run was started from
# this is more descriptive than the hostname as it also specifies who ran it
account_name: <ACCOUNT_NAME>

# path to store logs/checkpoints
output_path: <ROOT_PATH>/save
# path where pretrained models are stored
# model_path: <ROOT_PATH>/models

# datasets
global_dataset_paths:
  mesh_dataset: ${vars.data}/mesh_dataset
  shapenet_car: ${vars.data}/shapenet_car
  lagrangian_dataset: ${vars.data}/lagrangian_dataset

# OPTIONAL: path to (fast) local storage
# env:TMPDIR is not set when connecting via ssh to a compute node
local_dataset_path: <TMPDIR>

data_source_modes:
  mesh_dataset: global
  shapenet_car: global
  lagrangian_dataset: global

# wandb
# disabled -> don't use wandb
# offline -> use wandb in offline mode
# online -> use wandb in online mode
default_wandb_mode: offline

# DDP
master_port: 55555

# cudnn
default_cudnn_benchmark: true
default_cudnn_deterministic: false
# enable/disable cuda profiling
# - enabled: after every cuda operation to be profiled a torch.cuda.synchronize and dist.barrier is appended -> slower
# - disabled: cuda operations are not profiled
default_cuda_profiling: false
# sync batchnorm
default_sync_batchnorm: true
